# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170327_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash',
            field=models.FloatField(default=0),
        ),
    ]
