# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170327_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('token', models.FloatField(default=0)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
