# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
