# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170616_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
